# UGV Nav4D Planner Configuration

splineConfig:
  gridSize: 0.5
  numAngles: 16
  numEndAngles: 7
  destinationCircleRadius: 15
  cellSkipFactor: 1.0
  generatePointTurnMotions: false
  generateLateralMotions: false
  generateBackwardMotions: true
  generateForwardMotions: true
  splineOrder: 4

mobilityConfig:
  translationSpeed: 0.5
  rotationSpeed: 0.5
  minTurningRadius: 3.0
  searchRadius: 1.0
  searchProgressSteps: 0.1
  multiplierForward: 1
  multiplierForwardTurn: 4
  multiplierBackward: 2.0
  multiplierBackwardTurn: 4
  multiplierLateral: 4
  multiplierLateralCurve: 4
  multiplierPointTurn: 3
  maxMotionCurveLength: 100.0
  spline_sampling_resolution: 0.1
  remove_goal_offset: false
  curvaturePenaltyWeight: 3.0
  angularCostWeight: 3.0

travConfig:
  gridResolution: 0.5
  maxSlope: 0.45
  maxStepHeight: 0.45
  robotSizeX: 6.0
  robotSizeY: 3.0
  robotHeight: 3.0
  slopeMetricScale: 1.0
  slopeMetric: "NONE"
  inclineLimittingMinSlope: 0.22
  inclineLimittingLimit: 0.43
  costFunctionDist: 0.0
  distToGround: 0.0
  minTraversablePercentage: 0.4
  allowForwardDownhill: true
  enableInclineLimitting: false
  obstacleInflationMultiplier: 1.0
  partiallyTraversableMultiplier: 2.0


plannerConfig:
  epsilonSteps: 2.0
  initialEpsilon: 6.0
  numThreads: 4
  usePathStatistics: false
  searchUntilFirstSolution: false
  corridorWidth: 5.0
